/**
 * backend/tests/publishedFixture.test.ts
 *
 * Two guards on the three published example sites.
 *
 * 1. The copy of them the browser reads has to match the dataset. It was a file
 *    typed by hand, and when the demo numbers were reconciled with the July
 *    collection it still held Northern Virginia's land at $420,000 an acre
 *    against the dataset's $4.4M, and Nordic Hydro's build cost 2,095 a kW
 *    below the dataset. The home page argues from that file, so it would have
 *    argued against the data behind it. It is generated now, and this test
 *    fails if anyone edits it by hand or forgets to re-run the generator.
 *
 * 2. The engine's answer has to match plain arithmetic worked from the dataset
 *    with no engine code involved. Written out here longhand, once, so a
 *    refactor inside the engine cannot quietly move the published figures.
 */

import { describe, it, expect, beforeEach } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { runEngine } from '../src/engine/index.js'
import { _resetRegionsCache } from '../src/regions.js'
import {
  MAINTENANCE_RATE, BASE_STAFF_COST_PER_KW, BASE_CONNECTIVITY_PER_KW,
  ACRES_PER_MW, MIN_ACRES,
} from '../src/engine/assumptions.js'

const ROOT = resolve(import.meta.dirname, '../..')
const regions = JSON.parse(readFileSync(resolve(ROOT, 'data/regions.json'), 'utf8'))
const defaultSitesSrc = readFileSync(resolve(ROOT, 'frontend/src/data/defaultSites.ts'), 'utf8')

const SITES = ['eu-nordic-hydro', 'us-tx-ercot', 'us-va-northern'] as const

// ── 1. The browser's copy matches the dataset ─────────────────────────────────

describe('the published sites the browser reads', () => {
  it('is generated, not hand-maintained', () => {
    expect(defaultSitesSrc).toMatch(/GENERATED by scripts\/gen-default-sites\.mjs/)
  })

  const FIELDS: Array<[string, string]> = [
    ['powerRate',         'power_rate_usd_per_kwh'],
    ['waterRate',         'water_rate_usd_per_kgal'],
    ['landCostPerAcre',   'land_cost_per_acre_usd'],
    ['constructionPerKw', 'construction_cost_per_kw'],
    ['staffIndex',        'staff_cost_index'],
    ['taxRate',           'tax_rate'],
    ['taxAbatementYears', 'tax_abatement_years'],
  ]

  it.each(SITES)('%s carries the dataset values', (key) => {
    const block = defaultSitesSrc.split(`key: '${key}'`)[1]
    expect(block).toBeDefined()
    const body = block.split('},')[0]
    for (const [name, driver] of FIELDS) {
      const value = regions[key][driver]?.value
      if (value === null || value === undefined) continue
      expect(body).toContain(`${name}: ${value}`)
    }
  })

  it('carries no interconnection wait the dataset does not hold', () => {
    for (const key of SITES) {
      const body = defaultSitesSrc.split(`key: '${key}'`)[1].split('},')[0]
      const stored = regions[key].grid_interconnection_years?.value
      expect(body).toContain(`gridWaitYears: ${stored === null || stored === undefined ? 'null' : stored}`)
    }
  })
})

// ── 2. The engine matches arithmetic done by hand ─────────────────────────────

describe('the published figures, checked against longhand arithmetic', () => {
  beforeEach(() => { _resetRegionsCache() })

  const CAPACITY = 10_000
  const PUE      = 1.4
  const YEARS    = 15
  const RATE     = 0.08
  const WUE      = 0.4
  const LITRES_PER_KGAL = 3_785.4

  /** No engine code below this line. Straight out of the dataset. */
  function byHand(key: string) {
    const v = (driver: string, fallback = 0): number => {
      const x = regions[key][driver]?.value
      return x === null || x === undefined ? fallback : x
    }

    const acres = Math.max(MIN_ACRES, (CAPACITY / 1000) * ACRES_PER_MW)
    const capex = acres * v('land_cost_per_acre_usd') + CAPACITY * v('construction_cost_per_kw')

    const itEnergy   = CAPACITY * 8_760
    const totalPower = itEnergy * PUE
    const cooling    = itEnergy * (PUE - 1)

    const runningCost = (year: number): number =>
      totalPower * v('power_rate_usd_per_kwh')
      + (cooling * WUE / LITRES_PER_KGAL) * v('water_rate_usd_per_kgal')
      + CAPACITY * BASE_STAFF_COST_PER_KW * v('staff_cost_index', 1)
      + capex * MAINTENANCE_RATE
      // Regional incentive programs are not negotiated property-tax holidays.
      // With no explicit candidate-site override, property tax starts in year 1.
      + capex * v('tax_rate')
      + CAPACITY * BASE_CONNECTIVITY_PER_KW

    let discounted = 0
    for (let year = 1; year <= YEARS; year++) {
      discounted += runningCost(year) / Math.pow(1 + RATE, year)
    }

    return {
      capex,
      opexYear1:      runningCost(1),
      lifetimePerKw: (capex + discounted) / CAPACITY,
    }
  }

  it('the engine agrees with the arithmetic on all three sites', async () => {
    const out = await runEngine({
      request_id: '00000000-0000-0000-0000-000000000097',
      project: {
        name: 'Longhand check',
        capacity_kw: CAPACITY,
        design_pue: PUE,
        design_wue: WUE,
        lifetime_years: YEARS,
        discount_rate: RATE,
      },
      sites: [
        { site_id: 'nordic', label: 'Nordic Hydro',     region_key: 'eu-nordic-hydro' },
        { site_id: 'ercot',  label: 'Texas ERCOT',       region_key: 'us-tx-ercot'     },
        { site_id: 'nova',   label: 'Northern Virginia', region_key: 'us-va-northern'  },
      ],
    }, { forceFallback: true, skipCache: true })

    const pairs: Array<[string, string]> = [
      ['nordic', 'eu-nordic-hydro'],
      ['ercot',  'us-tx-ercot'],
      ['nova',   'us-va-northern'],
    ]

    for (const [siteId, regionKey] of pairs) {
      const hand = byHand(regionKey)
      const got  = out.sites[siteId]
      expect(got.capex.total_usd).toBeCloseTo(hand.capex, 0)
      expect(got.opex_annual.total_usd).toBeCloseTo(hand.opexYear1, 0)
      expect(got.finance.lifetime_cost_per_kw).toBeCloseTo(hand.lifetimePerKw, 0)
    }
  })

  it('Northern Virginia now costs about $16.2M a MW to build', async () => {
    const hand = byHand('us-va-northern')
    // A working operator put the market at $14M to $20M a MW. The build cost
    // here covers land and construction and stops there, so it is not the same
    // scope as an all-in figure. Land is what puts this market inside the range.
    expect(hand.capex / (CAPACITY / 1000) / 1e6).toBeGreaterThan(14)
    expect(hand.capex / (CAPACITY / 1000) / 1e6).toBeLessThan(20)
  })
})
