import type { EstimateInput } from '../schemas/input.js'
import type { EstimateOutput } from '../schemas/output.js'
import { v4 as uuidv4 } from 'uuid'

/**
 * Stub engine — returns a plausible hard-coded EstimateOutput.
 * Real cost logic will replace this in subsequent build steps.
 * The LLM layer is NOT called here; narrative is a placeholder string.
 */
export function runEngine(input: EstimateInput): EstimateOutput {
  const siteIds = input.sites.map((s) => s.site_id)

  // Build a stub output entry for each site
  const stubbedSites: EstimateOutput['sites'] = {}
  siteIds.forEach((id, i) => {
    stubbedSites[id] = {
      rank: i + 1,
      weighted_score: parseFloat((0.9 - i * 0.12).toFixed(3)),
      capex: {
        land_usd:         4_200_000,
        construction_usd: 85_000_000,
        electrical_usd:   12_000_000,
        cooling_usd:       9_500_000,
        it_fitout_usd:    18_000_000,
        total_usd:       128_700_000,
      },
      opex_annual: {
        power_usd:         9_200_000,
        water_usd:           420_000,
        staff_usd:         3_100_000,
        maintenance_usd:   1_800_000,
        taxes_usd:           950_000,
        connectivity_usd:    600_000,
        total_usd:        16_070_000,
      },
      finance: {
        levelized_cost_per_kw: 1842,
        npv_usd:               -198_000_000,
        payback_years:         7.4,
        ranges: {
          low:  { npv_usd: -178_000_000, levelized_per_kw: 1640 },
          base: { npv_usd: -198_000_000, levelized_per_kw: 1842 },
          high: { npv_usd: -231_000_000, levelized_per_kw: 2140 },
        },
      },
      non_cost_scores: {
        risk_score:    3.2,
        renewable_pct: 0.68,
        latency_ms:    14,
      },
    }
  })

  return {
    request_id:     input.request_id ?? uuidv4(),
    generated_at:   new Date().toISOString(),
    engine_version: '0.1.0-stub',
    ranking:        siteIds,
    sites:          stubbedSites,
    sensitivity: [
      {
        driver:         'power_rate_usd_per_kwh',
        current_value:  0.042,
        flip_value:     0.061,
        pct_change:     45.2,
        affected_sites: siteIds.slice(0, 2),
      },
    ],
    flip_sentence:
      'This ranking flips if power rates rise above $0.061/kWh (+45%).',
    narrative:
      '[Narrative will be generated by watsonx/Granite once the LLM module is wired in.]',
    data_provenance: input.sites.map((site) => ({
      region_key:    site.region_key,
      driver:        'power_rate_usd_per_kwh',
      value:         0.042,
      source_url:    'https://www.eia.gov/electricity/',
      last_verified: '2025-06',
    })),
  }
}
