// Regenerates src/data/intlRegions.ts from data/regions.json.
//
// The US snapshot (src/data/usRegions.ts) is produced by gen-geo.mjs and carries
// map coordinates. The 14 international regions never appear on the US map, so
// they are kept in their own file with no plotting coordinates. Both files use
// the same UsRegion shape so driversFor() reads either without a branch.
//
// Run from the frontend folder:  node scripts/gen-intl.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const regions = JSON.parse(readFileSync(resolve(here, '../../data/regions.json'), 'utf8'))

const DRIVERS = [
  'power_rate_usd_per_kwh', 'water_rate_usd_per_kgal', 'land_cost_per_acre_usd',
  'construction_cost_per_kw', 'staff_cost_index', 'tax_rate', 'tax_abatement_years',
  'incentive_usd_per_kw', 'risk_score', 'renewable_pct', 'latency_ms_to_hub',
  'grid_interconnection_years',
]

const out = []
for (const [key, r] of Object.entries(regions)) {
  if (key.startsWith('us-')) continue
  const drivers = {}
  for (const d of DRIVERS) {
    const cell = r[d]
    drivers[d] = cell && cell.value !== null && cell.value !== undefined
      ? { v: cell.value, basis: cell.basis ?? 'assumed', method: cell.method ?? null,
          source: cell.source_url ?? null, verified: cell.last_verified ?? null }
      : null
  }
  out.push({ key, label: r.label ?? key, precision: 'metro', parentState: null,
             lon: 0, lat: 0, x: -9999, y: -9999, drivers })
}
out.sort((a, b) => a.label.localeCompare(b.label))

writeFileSync(resolve(here, '../src/data/intlRegions.ts'),
  `// GENERATED by scripts/gen-intl.mjs from data/regions.json. Do not edit by hand.\n` +
  `// These regions are not plotted on the US map; x and y are sentinels.\n` +
  `import type { UsRegion } from './usRegions'\n\n` +
  `export const INTL_REGIONS: UsRegion[] = ${JSON.stringify(out)}\n`)

console.log(`wrote ${out.length} international regions`)
