// GENERATES src/data/usRegions.ts from data/regions.json plus data/us-geo.json.
//
// This script is the one that was missing. src/data/usRegions.ts carried a
// header saying it was "GENERATED by scripts/gen-geo.mjs", but that file had
// never been committed, so the snapshot could not be regenerated and drifted
// away from the canonical dataset. On 2026-08-28 the frontend disagreed with
// data/regions.json on 48 metro cells, including Atlanta land at $95,000 an
// acre against a canonical $430,657, and it could price only 7 US regions
// while the canonical data supported 13. The landing page read its coverage
// figures from regions.json and the map read them from here, so the site
// contradicted itself.
//
// Two inputs, and the split between them is the point:
//
//   data/regions.json   the authoritative driver values. Always wins.
//   frontend/data/us-geo.json
//                       map geometry (lon, lat and the projected x, y), the
//                       label, the precision and the parent state, none of
//                       which the canonical dataset carries. It also holds
//                       `fallbackDrivers`: the 100 state-level construction
//                       and latency cells that are derived in the frontend
//                       and have no canonical counterpart. A fallback is used
//                       ONLY where regions.json has no value for that cell.
//
// Run from the frontend folder:  node scripts/gen-geo.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const regions = JSON.parse(readFileSync(resolve(here, '../../data/regions.json'), 'utf8'))
const geo = JSON.parse(readFileSync(resolve(here, '../data/us-geo.json'), 'utf8'))

// The driver order usRegions.ts has always used. Kept so the regenerated file
// diffs cleanly against the snapshot it replaces.
const DRIVERS = [
  'power_rate_usd_per_kwh', 'construction_cost_per_kw', 'staff_cost_index',
  'latency_ms_to_hub', 'risk_score', 'renewable_pct', 'low_carbon_pct',
  'land_cost_per_acre_usd', 'tax_rate', 'grid_interconnection_years',
  'water_rate_usd_per_kgal', 'incentive_usd_per_kw', 'tax_abatement_years',
]

const out = []
let fromCanonical = 0, fromFallback = 0, emptyCells = 0

for (const [key, g] of Object.entries(geo)) {
  const r = regions[key]
  if (!r) {
    console.warn(`  skipped ${key}: present in us-geo.json, absent from regions.json`)
    continue
  }
  const drivers = {}
  for (const d of DRIVERS) {
    const cell = r[d]
    if (cell && cell.value !== null && cell.value !== undefined) {
      drivers[d] = {
        v: cell.value,
        basis: cell.basis ?? 'assumed',
        method: cell.method ?? null,
        source: cell.source_url ?? null,
        verified: cell.last_verified ?? null,
      }
      fromCanonical++
    } else if (g.fallbackDrivers && g.fallbackDrivers[d]) {
      // Derived in the frontend, no canonical counterpart. Carried through
      // unchanged, still labelled with whatever basis it was given.
      drivers[d] = g.fallbackDrivers[d]
      fromFallback++
    } else {
      drivers[d] = null
      emptyCells++
    }
  }
  out.push({
    key, label: g.label, precision: g.precision, parentState: g.parentState,
    lon: g.lon, lat: g.lat, x: g.x, y: g.y, drivers,
  })
}

// The four drivers a ranking cannot run without. Reported here so a regeneration
// that silently drops a region out of the priceable set is visible immediately.
const REQUIRED = ['construction_cost_per_kw', 'power_rate_usd_per_kwh',
  'staff_cost_index', 'land_cost_per_acre_usd']
const priceable = out.filter(r => REQUIRED.every(d => r.drivers[d])).map(r => r.key)

const BUILD_MODEL_METHOD = 'derived from the state staff cost index by least squares against the 7 sourced construction figures in this dataset; labor is the dominant source of regional variance in build cost. Not a published construction index.'

writeFileSync(resolve(here, '../src/data/usRegions.ts'),
  `// GENERATED by scripts/gen-geo.mjs from data/regions.json and data/us-geo.json.\n` +
  `// Do not edit by hand. Re-run after any ingest:  node scripts/gen-geo.mjs\n` +
  `//\n` +
  `// Driver values come from data/regions.json. Map geometry and the derived\n` +
  `// state-level build and latency cells come from data/us-geo.json.\n` +
  `export type Basis = 'sourced' | 'modeled' | 'assumed'\n` +
  `export interface DriverValue { v: number; basis: Basis; method: string | null; source: string | null; verified: string | null }\n` +
  `export interface UsRegion {\n` +
  `  key: string; label: string; precision: 'metro' | 'state'; parentState: string | null\n` +
  `  lon: number; lat: number; x: number; y: number\n` +
  `  drivers: Record<string, DriverValue | null>\n` +
  `}\n` +
  `export const US_REGIONS: UsRegion[] = ${JSON.stringify(out)}\n` +
  `export const US_METROS: UsRegion[] = US_REGIONS.filter(r => r.precision === 'metro')\n` +
  `export const US_STATES: UsRegion[] = US_REGIONS.filter(r => r.precision === 'state')\n` +
  `export const BUILD_MODEL_METHOD = ${JSON.stringify(BUILD_MODEL_METHOD)}\n`)

console.log(`wrote ${out.length} US regions`)
console.log(`  ${fromCanonical} cells from regions.json, ${fromFallback} derived fallbacks, ${emptyCells} empty`)
console.log(`  ${priceable.length} regions carry all four required drivers:`)
console.log(`  ${priceable.join(', ')}`)
