// GENERATED by scripts/gen-coverage.mjs from data/regions.json. Do not edit by hand.
// Re-run after any ingest so the page never overstates or understates itself.
export const COVERAGE = {
  "regions": 77,
  "drivers": 13,
  "cells": 1001,
  "sourced": 279,
  "modeled": 275,
  "assumed": 0,
  "empty": 447,
  "priceable": 13,
  "parcels": 3040
} as const
