// GENERATED by scripts/gen-coverage.mjs from data/regions.json. Do not edit by hand.
// Re-run after any ingest so the page never overstates or understates itself.
export const COVERAGE = {
  "regions": 77,
  "drivers": 13,
  "cells": 1001,
  "sourced": 296,
  "modeled": 271,
  "assumed": 4,
  "empty": 430,
  "priceable": 14
} as const
