// GENERATED by scripts/gen-default-sites.mjs from data/regions.json.
// Do not edit by hand. Re-run the script after any change to the dataset.
//
// Nordic Hydro is not on the US map, so it is carried here rather than in
// usRegions. Place names are the only values not read from the dataset.
import type { SiteDrivers } from '../lib/engine'

export interface NamedSite { key: string; label: string; place: string; base: SiteDrivers }

export const DEFAULT_SITES: NamedSite[] = [
  {
    key: 'eu-nordic-hydro', label: 'Nordic Hydro', place: 'Luleå and Boden, Sweden',
    base: { powerRate: 0.024, waterRate: 1.1, landCostPerAcre: 18000, constructionPerKw: 12295, staffIndex: 1.35, taxRate: 0.022, taxAbatementYears: 0, incentivePerKw: 30, riskScore: 1.2, renewablePct: 0.97, latencyMs: 42, gridWaitYears: null },
  },
  {
    key: 'us-tx-ercot', label: 'Texas ERCOT', place: 'Hays County, Texas',
    base: { powerRate: 0.038, waterRate: 3.2, landCostPerAcre: 55000, constructionPerKw: 9540, staffIndex: 0.96, taxRate: 0.019, taxAbatementYears: 10, incentivePerKw: 220, riskScore: 5.8, renewablePct: 0.42, latencyMs: 22, gridWaitYears: null },
  },
  {
    key: 'us-va-northern', label: 'Northern Virginia', place: 'Loudoun County, Virginia',
    base: { powerRate: 0.068, waterRate: 7.59, landCostPerAcre: 4400000, constructionPerKw: 10920, staffIndex: 1.18, taxRate: 0.0081, taxAbatementYears: 9, incentivePerKw: 50, riskScore: 2, renewablePct: 0.2, latencyMs: 4, gridWaitYears: 3.2 },
  },
]
